version: "3.7"

x-defaults:
  network: &network
    networks:
      - net

services:
  php:
    image: jmac/php:7.4-apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - workspace:/var/www
    configs:
      - source: apache-vhosts
        target: /etc/apache2/sites-available/000-default.conf
      - source: php-ini
        target: /usr/local/etc/php/conf.d/local.ini
    <<: *network

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_pwd
    volumes:
      - data:/var/lib/mysql
    secrets:
      - db_pwd
    <<: *network


networks:
  net:

secrets:
  db_pwd:
    file: ./mysql/root_password.txt

configs:
  apache-vhosts:
    file: ./apache/vhosts.conf
  php-ini:
    file: ./php/local.ini

volumes: 
  workspace:
     external: true 
  data:
     external: true
